# Site settings
title: Benny's Mind Hack
email: btscheung@gmail.com
description: >
  Programming a computer to draw surely teaches us the most important lesson that creative spirit is in the details.
baseurl: # the subpath of your site, e.g. /blog/
# paginate: 10
url: "https://bennycheung.github.io" # the base hostname & protocol for your site

# Google Analytics
google_analytics: UA-76691604-1

# Comments settings
# DISQUS removed 2025-12-25 - forced advertising
# disqus_shortname: bennycheungmindhackblog

# Giscus comments (GitHub Discussions)
giscus:
  repo: bennycheung/bennycheung.github.io
  repo_id: R_kgDOAcxX0Q
  category: Comments
  category_id: DIC_kwDOAcxX0c4ClodK
  mapping: pathname
  strict: 0
  reactions_enabled: 1
  emit_metadata: 0
  input_position: bottom
  theme: preferred_color_scheme
  lang: en

# Social settings
avatar: /assets/avtar.jpg
twitter_username: Benny_Cheung
github_username: bennycheung
stackoverflow_username: users/6242759/benny-cheung
facebook_username: benny.cheung.9
linkedin_username: becheung
reddit_username : btscheung
stackoverflow_username : 6242759/benny-cheung
youtube_username : UC_y9pExhrufOEeucdHVi-Sw
email: btscheung@gmail.com

# comments:
#   provider: disqus
#   disqus:
#     short_name: bennycheungmindhackblog

gems:
  - jekyll-sitemap

# Front Matter Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      image: images/default-cover.jpg
      images:
        cover: images/default-cover-2x.jpg
        header: images/default-header.jpg

# Build settings
markdown: kramdown
# markdown: maruku

# Sass settings
sass:
  style: :compressed
